import AppKit
import Combine

class ClipboardMonitor: ObservableObject {
    static let shared = ClipboardMonitor()
    
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Content of the most recent text/url capture, to skip exact duplicates
    /// (e.g. copying the same thing repeatedly) instead of making identical cards.
    private var lastCapturedText: String?
    
    let onNewContent = PassthroughSubject<MemoryObject, Never>()
    
    private init() {}
    
    func start() {
        print("📋 ClipboardMonitor: Starting...")
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
        // Ensure it runs even when menus are open
        RunLoop.main.add(timer!, forMode: .common)
    }
    
    func stop() {
        print("📋 ClipboardMonitor: Stopping...")
        timer?.invalidate()
        timer = nil
    }

    /// Writes a string to the pasteboard without re-capturing it as a new
    /// memory. Used by in-app "copy" actions so they don't create duplicates.
    func writeWithoutCapture(_ string: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }
    
    private func checkClipboard() {
        let pasteboard = NSPasteboard.general
        // print("📋 Checking clipboard... count: \(pasteboard.changeCount)") 
        guard pasteboard.changeCount != lastChangeCount else { return }
        print("📋 Clipboard Change Detected! Count: \(pasteboard.changeCount)")
        lastChangeCount = pasteboard.changeCount
        
        processClipboard(pasteboard)
    }
    
    /// Pasteboard types that mark sensitive or throwaway content. Password
    /// managers set ConcealedType; transient/auto-generated cover ephemeral data.
    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]

    private func processClipboard(_ pasteboard: NSPasteboard) {
        let settings = SettingsStore.shared

        // Privacy gate 1: skip concealed/transient clipboard (e.g. passwords).
        if settings.ignoreConcealed,
           let types = pasteboard.types,
           Self.sensitiveTypes.contains(where: { types.contains($0) }) {
            print("🔒 Skipped concealed/transient clipboard")
            return
        }

        // Source app — read once, used for the exclusion gate and metadata.
        let sourceApp = NSWorkspace.shared.frontmostApplication

        // Privacy gate 2: skip apps the user excluded (e.g. password managers).
        if let bundleID = sourceApp?.bundleIdentifier,
           settings.excludedBundleIDs.contains(bundleID) {
            #if DEBUG
            print("🚫 Skipped excluded app: \(bundleID)")
            #endif
            return
        }

        var newObject: MemoryObject?

        // 1. Image — only when the pasteboard actually carries image data.
        //    (readObjects(forClasses: [NSImage.self]) is greedy and also
        //    matches plain text, so we gate on a real image UTType.)
        if pasteboard.availableType(from: [.tiff, .png]) != nil,
           let image = NSImage(pasteboard: pasteboard) {
            var object = MemoryObject(type: .image, content: "Image")
            let stored = ImageStore.persist(image, id: object.id)
            object.content = stored.asset ?? "Image"
            object.thumbnailPath = stored.thumbnail
            object.preview = "Image"
            newObject = object
            print("🖼️ Captured Image")
        }
        // 2. URL — a single-line string that parses as a web URL.
        else if let text = pasteboard.string(forType: .string),
                !text.contains(where: { $0.isWhitespace }),
                let url = URL(string: text),
                let scheme = url.scheme?.lowercased(),
                scheme == "http" || scheme == "https" {
            newObject = MemoryObject(type: .url, content: text)
            #if DEBUG
            // URLs frequently carry tokens/secrets — log length, never the URL.
            print("🔗 Captured URL (\(text.count) chars)")
            #endif
        }
        // 3. Fallback to plain text.
        else if let text = pasteboard.string(forType: .string) {
            newObject = MemoryObject(type: .text, content: text)
            #if DEBUG
            print("📝 Captured text (\(text.count) chars)")
            #endif
        }

        if var object = newObject {
            // Skip an exact repeat of the previous text/url capture.
            if object.type == .text || object.type == .url {
                if object.content == lastCapturedText { return }
                lastCapturedText = object.content
            }
            object.sourceApp = sourceApp?.localizedName
            if let bundleID = sourceApp?.bundleIdentifier {
                object.metadata["sourceBundleID"] = bundleID
            }
            onNewContent.send(object)
        }
    }
}
